# Generated by Django 3.0.6 on 2020-05-07 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200506_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
