# Generated by Django 3.0.6 on 2020-05-11 18:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontactinfo',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
