# Generated by Django 3.0.6 on 2020-05-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200511_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('cvv', models.IntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
            ],
        ),
    ]
