# Generated by Django 3.0.6 on 2020-05-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderpaymentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercontactinfo',
            old_name='street_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='ordercontactinfo',
            name='house_number',
        ),
    ]
