# Generated by Django 3.0.6 on 2020-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200512_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
