# Generated by Django 3.0.6 on 2020-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentinfo',
            name='expiry_month',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=2),
        ),
    ]
