# Generated by Django 3.0.6 on 2020-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200514_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentinfo',
            name='expiry_year',
            field=models.CharField(choices=[('1', '2020'), ('2', '2021'), ('3', '2022'), ('4', '2023'), ('5', '2024'), ('6', '2025'), ('7', '2026'), ('8', '2027'), ('9', '2028')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='orderpaymentinfo',
            name='expiry_month',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='01', max_length=2),
        ),
    ]
