# Generated by Django 3.0.6 on 2020-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200514_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaymentinfo',
            name='cvv',
        ),
        migrations.AddField(
            model_name='orderpaymentinfo',
            name='cvc',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpaymentinfo',
            name='expiry_year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], default='1', max_length=4),
        ),
    ]
